// Seeds SIDCUL Manufacturers Association head-wise member directory
// (from "HEAD WISE MEMBERS LIST11.xlsx") into the DirectoryCompany table.
// Additive/idempotent — upserts by sourceUrl, does not touch other directory
// categories (e.g. the scraped IT Park companies or the pharma-only list).
// Run with: npx tsx scripts/seed-members-directory.ts
import "dotenv/config";
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const MEMBERS = [
  {
    name: "MUNJAL SHOWA LTD.",
    slug: "munjal-showa-ltd",
    category: "Automobile & Auto Component",
    address: "PLOT NO-1, IP-2, PHASE 1, SALEMPUR MEHDOOD, HARIDWAR",
    phone: "9718072073",
    description: "Contact: MR. ANKUR DUBEY",
    sourceUrl: "local://members-directory/automobile-auto-component/munjal-showa-ltd",
  },
  {
    name: "M/s Neel Metal Products Limited",
    slug: "m-s-neel-metal-products-limited",
    category: "Automobile & Auto Component",
    address: "Plot No 4-6  11-16, Ground, Neel Metal Products Ltd, Sec-5 Iie Sidcul, Sidcul Haridwar, Haridwar",
    phone: "8859320030",
    description: "Contact: MR. ADITYA PRAKASH UPADHYAY",
    sourceUrl: "local://members-directory/automobile-auto-component/m-s-neel-metal-products-limited",
  },
  {
    name: "Makino Automotive",
    slug: "makino-automotive",
    category: "Automobile & Auto Component",
    address: "C-1,D1-D2,Industrial Area Bahadrabad",
    phone: "9805841767",
    description: "Contact: MR. PANKAJ CHAUHAN",
    sourceUrl: "local://members-directory/automobile-auto-component/makino-automotive",
  },
  {
    name: "Rockman Industries Ltd.",
    slug: "rockman-industries-ltd",
    category: "Automobile & Auto Component",
    address: "Plot No.3/p1,Sector-10,Iie Sidcul Haridwar",
    phone: "7500313300",
    description: "Contact: MR. RAJEEV CHAUHAN",
    sourceUrl: "local://members-directory/automobile-auto-component/rockman-industries-ltd",
  },
  {
    name: "SHAYAM AUTO",
    slug: "shayam-auto",
    category: "Automobile & Auto Component",
    address: "ROORKEE HARIDWAR",
    phone: null,
    description: null,
    sourceUrl: "local://members-directory/automobile-auto-component/shayam-auto",
  },
  {
    name: "TAKSHI AUTO COMPONENTS PVT.LTD.",
    slug: "takshi-auto-components-pvt-ltd",
    category: "Automobile & Auto Component",
    address: ",SECTOR-IIDC,SIDCUL HARIDWAR",
    phone: "9758024545",
    description: "Contact: AMIT KUMAR",
    sourceUrl: "local://members-directory/automobile-auto-component/takshi-auto-components-pvt-ltd",
  },
  {
    name: "U.S.METAL PRODUCTS",
    slug: "u-s-metal-products",
    category: "Automobile & Auto Component",
    address: "PLOT NO.78,SECTOR-5,SIDCUL HARIDWAR",
    phone: "8171009999",
    description: "Contact: R.K.SUNEJA",
    sourceUrl: "local://members-directory/automobile-auto-component/u-s-metal-products",
  },
  {
    name: "MEENAKSHI POLYMERS PVT.LTD.",
    slug: "meenakshi-polymers-pvt-ltd",
    category: "Automobile & Auto Component",
    address: "PLOT NO.10,SE TOR-8A,SIDCUL HARIDWAR",
    phone: "9319577801",
    description: "Contact: PRASHANT GUPTA",
    sourceUrl: "local://members-directory/automobile-auto-component/meenakshi-polymers-pvt-ltd",
  },
  {
    name: "HI-CASTING & ENGINEERINGS",
    slug: "hi-casting-engineerings",
    category: "Automobile & Auto Component",
    address: "PLOT NO.65&89,SECTOR-7,SIDCUL HARIDWAR",
    phone: "9810570791",
    description: "Contact: DHURV GUPTA",
    sourceUrl: "local://members-directory/automobile-auto-component/hi-casting-engineerings",
  },
  {
    name: "LAREX AUTO",
    slug: "larex-auto",
    category: "Automobile & Auto Component",
    address: "INDUSTRIAL AREA BAHADRABAD",
    phone: "8791333300",
    description: "Contact: SHIV CHANDRA YADAV",
    sourceUrl: "local://members-directory/automobile-auto-component/larex-auto",
  },
  {
    name: "MINDA CORPORATION",
    slug: "minda-corporation",
    category: "Automobile & Auto Component",
    address: "PLOT NO-19-20,SECTOR-8A,SIDCUL HARIDWAR",
    phone: "8392927474",
    description: "Contact: ALOK PUNDIR",
    sourceUrl: "local://members-directory/automobile-auto-component/minda-corporation",
  },
  {
    name: "Auto Components Pvt.Ltd.",
    slug: "auto-components-pvt-ltd",
    category: "Automobile & Auto Component",
    address: "Plot No.27,Sector-4,Sidcul Haridwar",
    phone: "89410 20304",
    description: "Contact: Mr.NEELMANI SRIVASTAV Ji",
    sourceUrl: "local://members-directory/automobile-auto-component/auto-components-pvt-ltd",
  },
  {
    name: "CAVENDISH INDUSTRIES(J.K.TYRE)",
    slug: "cavendish-industries-j-k-tyre",
    category: "Automobile & Auto Component",
    address: "LAKSAR HARIDWAR",
    phone: "9634984167",
    description: "Contact: MR.DHEERAJ SHARMA",
    sourceUrl: "local://members-directory/automobile-auto-component/cavendish-industries-j-k-tyre",
  },
  {
    name: "A Robotics Automation Solution",
    slug: "a-robotics-automation-solution",
    category: "Automobile & Auto Component",
    address: "IP-2,SALEMPUR MEHDOOD HARIDWAR",
    phone: "9319676536",
    description: "Contact: MR.ANKUR JI",
    sourceUrl: "local://members-directory/automobile-auto-component/a-robotics-automation-solution",
  },
  {
    name: "Manhari Corporation",
    slug: "manhari-corporation",
    category: "Electrical & Electric Component,Power",
    address: "Plot No.129,Sector-6a,Sidcul Haridwar",
    phone: "752029206",
    description: "Contact: MR. PULKIT GARG",
    sourceUrl: "local://members-directory/electrical-electric-component-power/manhari-corporation",
  },
  {
    name: "Omnia Apliances",
    slug: "omnia-apliances",
    category: "Electrical & Electric Component,Power",
    address: "Plot No.9,Sector-6a,IIE Sidcul Haridwar",
    phone: "9411111992",
    description: "Contact: MR. ANKUR GUPTA",
    sourceUrl: "local://members-directory/electrical-electric-component-power/omnia-apliances",
  },
  {
    name: "Rj Industrial Corporation",
    slug: "rj-industrial-corporation",
    category: "Electrical & Electric Component,Power",
    address: "1-2,Industrial Estate ,Roorkee",
    phone: "9897049494",
    description: "Contact: MR. PIYUSH JINDAL",
    sourceUrl: "local://members-directory/electrical-electric-component-power/rj-industrial-corporation",
  },
  {
    name: "Samriddhi Automations Pvt,Ltd.",
    slug: "samriddhi-automations-pvt-ltd",
    category: "Electrical & Electric Component,Power",
    address: "Plot No.75,Sector-7,IIE Sidcul Haridwar",
    phone: "9219619369",
    description: "Contact: MR. BALVENDRA",
    sourceUrl: "local://members-directory/electrical-electric-component-power/samriddhi-automations-pvt-ltd",
  },
  {
    name: "Siddhi Vinayak Industries",
    slug: "siddhi-vinayak-industries",
    category: "Electrical & Electric Component,Power",
    address: "Plot No.28b,Sector-3,Sidcul Haridwar",
    phone: "9719009461",
    description: "Contact: MR. ASHISH GUPTA",
    sourceUrl: "local://members-directory/electrical-electric-component-power/siddhi-vinayak-industries",
  },
  {
    name: "M-TECH EQUIPMENT",
    slug: "m-tech-equipment",
    category: "Electrical & Electric Component,Power",
    address: "INDUSTRIAL AREA BAHADRABAD HARIDWAR",
    phone: "9837042122",
    description: "Contact: ASHISH PAWANJAI",
    sourceUrl: "local://members-directory/electrical-electric-component-power/m-tech-equipment",
  },
  {
    name: "WONDER ELECTRICALS LTD.",
    slug: "wonder-electricals-ltd",
    category: "Electrical & Electric Component,Power",
    address: "PLOT NO.33SECTOR-8A,SIDCUL HARIDWAR",
    phone: "7351003417",
    description: "Contact: G.N.GODIYAL",
    sourceUrl: "local://members-directory/electrical-electric-component-power/wonder-electricals-ltd",
  },
  {
    name: "V-MARC INDIA LTD.",
    slug: "v-marc-india-ltd",
    category: "Electrical & Electric Component,Power",
    address: "PLOT NO-3-4,SECTOR-IIDC,SIDCUL HARIDWAR",
    phone: "9319796600",
    description: "Contact: ABHAY GOEL",
    sourceUrl: "local://members-directory/electrical-electric-component-power/v-marc-india-ltd",
  },
  {
    name: "PANASONIC LIFE SOLUTION",
    slug: "panasonic-life-solution",
    category: "Electrical & Electric Component,Power",
    address: "PLOT NO.1B,SECTOR-8B,SIDCUL HARIDWAR",
    phone: "9359535353",
    description: "Contact: ASHISH PRASHAR",
    sourceUrl: "local://members-directory/electrical-electric-component-power/panasonic-life-solution",
  },
  {
    name: "ANDS LITE PVT.LTD.",
    slug: "ands-lite-pvt-ltd",
    category: "Electrical & Electric Component,Power",
    address: "PLOT NO.1D-48-51,SECTOR-7,SIDCUL HARIDWAR",
    phone: "9997871234",
    description: "Contact: PANKAJ SAHOO",
    sourceUrl: "local://members-directory/electrical-electric-component-power/ands-lite-pvt-ltd",
  },
  {
    name: "PM CONA INDUSTRIES",
    slug: "pm-cona-industries",
    category: "Electrical & Electric Component,Power",
    address: "PLOT NO.12,SECTOR-12,SIDCUL HARIDWAR",
    phone: "9759728011",
    description: "Contact: JAY PATEL",
    sourceUrl: "local://members-directory/electrical-electric-component-power/pm-cona-industries",
  },
  {
    name: "DESIGNTECH",
    slug: "designtech",
    category: "Electrical & Electric Component,Power",
    address: "PLOT NO.30A1,SECTOR-11,SIDCUL HARIDWAR",
    phone: "9319023775",
    description: "Contact: VISHAL PUNDIR",
    sourceUrl: "local://members-directory/electrical-electric-component-power/designtech",
  },
  {
    name: "GANGA METCO",
    slug: "ganga-metco",
    category: "Electrical & Electric Component,Power",
    address: "PLOT N.19A,IP-2,SALEMPUR MEHDOOD",
    phone: "8859004225",
    description: "Contact: NITESH JAIN",
    sourceUrl: "local://members-directory/electrical-electric-component-power/ganga-metco",
  },
  {
    name: "ASSOCIATES ELECTRICALS",
    slug: "associates-electricals",
    category: "Electrical & Electric Component,Power",
    address: "PLOT NO.25-26,SECTOR-IIDC,SIDCUL HARIDWAR",
    phone: "9350597172",
    description: "Contact: ABHISHEK",
    sourceUrl: "local://members-directory/electrical-electric-component-power/associates-electricals",
  },
  {
    name: "Advance Panel & Switchgears Pvt.Ltd.",
    slug: "advance-panel-switchgears-pvt-ltd",
    category: "Electrical & Electric Component,Power",
    address: "Plot No.30-31,Sector-5,Sidcul Haridwar",
    phone: "78305 55501",
    description: "Contact: Mr.Rahul Singhvi JI",
    sourceUrl: "local://members-directory/electrical-electric-component-power/advance-panel-switchgears-pvt-ltd",
  },
  {
    name: "Affine Steel Pvt.Ltd.",
    slug: "affine-steel-pvt-ltd",
    category: "Electrical & Electric Component,Power",
    address: "Plot No.98,Sector-7,Sidcul Haridwar",
    phone: "98370 06016",
    description: "Contact: Mr.Lokesh Lohia JI",
    sourceUrl: "local://members-directory/electrical-electric-component-power/affine-steel-pvt-ltd",
  },
  {
    name: "AMPHI Plasto Pvt Ltd",
    slug: "amphi-plasto-pvt-ltd",
    category: "Electrical & Electric Component,Power",
    address: "D-134,INDUSTRIAL AREA BAHADRABAD",
    phone: "9377962672",
    description: "Contact: MR.AJAY RAI  Ji",
    sourceUrl: "local://members-directory/electrical-electric-component-power/amphi-plasto-pvt-ltd",
  },
  {
    name: "Anuvidyut Pvt.Ltd.",
    slug: "anuvidyut-pvt-ltd",
    category: "Electrical & Electric Component,Power",
    address: "C-1,Industrial Estate Ramnagar,Roorkee, Haridwar",
    phone: "98970 62545",
    description: "Contact: Mr.Vandana Mohan JI",
    sourceUrl: "local://members-directory/electrical-electric-component-power/anuvidyut-pvt-ltd",
  },
  {
    name: "Elleys Industries (India) Pvt Ltd",
    slug: "elleys-industries-india-pvt-ltd",
    category: "Electrical & Electric Component,Power",
    address: "Plot No.54-58,Sector-8a,Sidcul Haridwar",
    phone: "93592 96403",
    description: "Contact: Mr.Laher Haria Ji",
    sourceUrl: "local://members-directory/electrical-electric-component-power/elleys-industries-india-pvt-ltd",
  },
  {
    name: "G-Lite Power Technology",
    slug: "g-lite-power-technology",
    category: "Electrical & Electric Component,Power",
    address: "Plot No.10,Sector-Iidc,Sidcul Haridwar",
    phone: "98976 37139",
    description: "Contact: Mr.SPS Gautam Ji",
    sourceUrl: "local://members-directory/electrical-electric-component-power/g-lite-power-technology",
  },
  {
    name: "GRUNER India Pvt. Ltd",
    slug: "gruner-india-pvt-ltd",
    category: "Electrical & Electric Component,Power",
    address: "PLOT NO.25,SECTOR-8A,SIDCUL HARIDWAR",
    phone: "99176 26404",
    description: "Contact: Mr.Sachin Jain Ji",
    sourceUrl: "local://members-directory/electrical-electric-component-power/gruner-india-pvt-ltd",
  },
  {
    name: "Hartech Electronics",
    slug: "hartech-electronics",
    category: "Electrical & Electric Component,Power",
    address: "Plot No.1,Sector-12,Sidcul Haridwar",
    phone: "81940 02400",
    description: "Contact: Mr.Amit Ji",
    sourceUrl: "local://members-directory/electrical-electric-component-power/hartech-electronics",
  },
  {
    name: "Hpm-Innotech Pvt.Ltd.",
    slug: "hpm-innotech-pvt-ltd",
    category: "Electrical & Electric Component,Power",
    address: "E-64,Industrial Area Bahadrabad,Haridwar",
    phone: "97596 31320",
    description: "Contact: Mr.Piyush Chaudhary Ji",
    sourceUrl: "local://members-directory/electrical-electric-component-power/hpm-innotech-pvt-ltd",
  },
  {
    name: "KALPA PVT LTD",
    slug: "kalpa-pvt-ltd",
    category: "Electrical & Electric Component,Power",
    address: "PLOT NO-D19 BAHADRABAD, Haridwar",
    phone: "8791222200",
    description: "Contact: MR.NAVNEET SHARMA Ji",
    sourceUrl: "local://members-directory/electrical-electric-component-power/kalpa-pvt-ltd",
  },
  {
    name: "M/s Luminous Power Technologies Pvt Ltd",
    slug: "m-s-luminous-power-technologies-pvt-ltd",
    category: "Electrical & Electric Component,Power",
    address: "Plot No.4,Sector-12,Sidcul Haridwar",
    phone: "75084 46144",
    description: "Contact: Mr.Shiv Sahai Pal Ji",
    sourceUrl: "local://members-directory/electrical-electric-component-power/m-s-luminous-power-technologies-pvt-ltd",
  },
  {
    name: "Hpm-Innotech Pvt.Ltd.",
    slug: "hpm-innotech-pvt-ltd",
    category: "Electrical & Electric Component,Power",
    address: "E-64,Industrial Area Bahadrabad,Haridwar",
    phone: null,
    description: null,
    sourceUrl: "local://members-directory/electrical-electric-component-power/hpm-innotech-pvt-ltd",
  },
  {
    name: "Genus Power infrostructures ltd",
    slug: "genus-power-infrostructures-ltd",
    category: "Electrical & Electric Component,Power",
    address: "Plot No.12 Sec-4,SIDCUL",
    phone: "9257031435",
    description: "Contact: VIJAY MISHRA",
    sourceUrl: "local://members-directory/electrical-electric-component-power/genus-power-infrostructures-ltd",
  },
  {
    name: "NEELGIRI ELECTRICAL",
    slug: "neelgiri-electrical",
    category: "Electrical & Electric Component,Power",
    address: "PLOT NO.-21,SECTOR-8A,SIDCUL,HARIDWAR",
    phone: "9719625500",
    description: "Contact: PRAVEEN DAVID",
    sourceUrl: "local://members-directory/electrical-electric-component-power/neelgiri-electrical",
  },
  {
    name: "HAVELLS INDIA",
    slug: "havells-india",
    category: "Electrical & Electric Component,Power",
    address: "PLOT NO.1/P1,SEC-10,SIDCUL",
    phone: "8755587444",
    description: "Contact: SANJEEV PRASHAR",
    sourceUrl: "local://members-directory/electrical-electric-component-power/havells-india",
  },
  {
    name: "Elza",
    slug: "elza",
    category: "Electrical & Electric Component,Power",
    address: "Plot No-94A Sec-6A,SIDCUL",
    phone: "7720000006/9810129011",
    description: "Contact: AVIRATH KAPOOR/ASHVANI KAPOOR",
    sourceUrl: "local://members-directory/electrical-electric-component-power/elza",
  },
  {
    name: "Kolors India Pvt Ltd",
    slug: "kolors-india-pvt-ltd",
    category: "Electrical & Electric Component,Power",
    address: "Plot No.32.33 sec-4,SIDCUL",
    phone: "9359259688",
    description: null,
    sourceUrl: "local://members-directory/electrical-electric-component-power/kolors-india-pvt-ltd",
  },
  {
    name: "KKG INDUSTRIES",
    slug: "kkg-industries",
    category: "Electrical & Electric Component,Power",
    address: "PLOT NO.31,SEC-3A Sidcul Haridwar",
    phone: "9411141235",
    description: "Contact: Mr.VIPIN SISODIA Ji",
    sourceUrl: "local://members-directory/electrical-electric-component-power/kkg-industries",
  },
  {
    name: "SUPER INDUSTRIES",
    slug: "super-industries",
    category: "Electrical & Electric Component,Power",
    address: "PLOT NO-9A-9B,IP-2,SALEMPUR MEHDOOD",
    phone: "9927430980",
    description: "Contact: MR.AMIT GOYAL JI",
    sourceUrl: "local://members-directory/electrical-electric-component-power/super-industries",
  },
  {
    name: "POWERTECH",
    slug: "powertech",
    category: "Electrical & Electric Component,Power",
    address: "ROORKEE HARIDWAR",
    phone: "9412486899",
    description: "Contact: MR.AMIT GOEL JI",
    sourceUrl: "local://members-directory/electrical-electric-component-power/powertech",
  },
  {
    name: "MAHESHWARI PHARMACEUTICALS",
    slug: "maheshwari-pharmaceuticals",
    category: "Pharma Cosmetic & Ayush/HEALTHCARE",
    address: "PLOT NO.7,SECTOR-6B,SIDCUL HARIDWAR",
    phone: "9319074663",
    description: "Contact: MR. DEPAK MAHESHWARI",
    sourceUrl: "local://members-directory/pharma-cosmetic-ayush-healthcare/maheshwari-pharmaceuticals",
  },
  {
    name: "Mallcom India Ltd.",
    slug: "mallcom-india-ltd",
    category: "Pharma Cosmetic & Ayush/HEALTHCARE",
    address: "Plot No.32,Sector-3a,IIE Sidcul Haridwar",
    phone: "8279520368",
    description: "Contact: MR. SANDEP KUMAR",
    sourceUrl: "local://members-directory/pharma-cosmetic-ayush-healthcare/mallcom-india-ltd",
  },
  {
    name: "MASCOT",
    slug: "mascot",
    category: "Pharma Cosmetic & Ayush/HEALTHCARE",
    address: "PLOT NO.68,SECTOR-6A,SIDCUL HARIDWAR",
    phone: "9690008744",
    description: "Contact: MR. Jai veer tyagi",
    sourceUrl: "local://members-directory/pharma-cosmetic-ayush-healthcare/mascot",
  },
  {
    name: "Matins Healthcare Pvt.Ltd.",
    slug: "matins-healthcare-pvt-ltd",
    category: "Pharma Cosmetic & Ayush/HEALTHCARE",
    address: "Plot No.10,Sector-5,Sidcul Haridwar",
    phone: "9810121951",
    description: "Contact: MR. VINAY SHRIDHAR",
    sourceUrl: "local://members-directory/pharma-cosmetic-ayush-healthcare/matins-healthcare-pvt-ltd",
  },
  {
    name: "Multani Pharmaceuticals Ltd.",
    slug: "multani-pharmaceuticals-ltd",
    category: "Pharma Cosmetic & Ayush/HEALTHCARE",
    address: "Khasra No.37,Bhagwanpur Roorkee,Makkanpur, Mehmood Alam,Haridwar",
    phone: "9654350707",
    description: "Contact: MR. VINAY ROONGTA",
    sourceUrl: "local://members-directory/pharma-cosmetic-ayush-healthcare/multani-pharmaceuticals-ltd",
  },
  {
    name: "Nishant Aroma",
    slug: "nishant-aroma",
    category: "Pharma Cosmetic & Ayush/HEALTHCARE",
    address: "Plot No 30, 31 & 61, IIE Sector 1B Sidcul Haridwar",
    phone: "9997388361",
    description: "Contact: MS. NEHA",
    sourceUrl: "local://members-directory/pharma-cosmetic-ayush-healthcare/nishant-aroma",
  },
  {
    name: "Pharmasynth Formulation",
    slug: "pharmasynth-formulation",
    category: "Pharma Cosmetic & Ayush/HEALTHCARE",
    address: "Plot No.18-22,Sector-6b,Sidcul Haridwar",
    phone: "9319777674",
    description: "Contact: MR. R.C.JAIN",
    sourceUrl: "local://members-directory/pharma-cosmetic-ayush-healthcare/pharmasynth-formulation",
  },
  {
    name: "PRISM PLATES",
    slug: "prism-plates",
    category: "Pharma Cosmetic & Ayush/HEALTHCARE",
    address: "PLOT NO-31-32,2nd FLOOR ,SEC-IIDC",
    phone: "9775090003",
    description: "Contact: MR. MAHENDRA SINGH",
    sourceUrl: "local://members-directory/pharma-cosmetic-ayush-healthcare/prism-plates",
  },
  {
    name: "Pritam International Pvt.Ltd.",
    slug: "pritam-international-pvt-ltd",
    category: "Pharma Cosmetic & Ayush/HEALTHCARE",
    address: "Khasra No.138,Raipur Industrial Area,Bhagwanpur, Roorkee",
    phone: "7088103801",
    description: "Contact: MR. KULDEP VERMA",
    sourceUrl: "local://members-directory/pharma-cosmetic-ayush-healthcare/pritam-international-pvt-ltd",
  },
  {
    name: "Psychotropics India Ltd.",
    slug: "psychotropics-india-ltd",
    category: "Pharma Cosmetic & Ayush/HEALTHCARE",
    address: "Plot No.46-49,Sector-6a,IIE Sidcul Haridwar",
    phone: "8272011171",
    description: "Contact: MR. SUNIL CHAUDHARY",
    sourceUrl: "local://members-directory/pharma-cosmetic-ayush-healthcare/psychotropics-india-ltd",
  },
  {
    name: "PURE & CURE (AKUMS)",
    slug: "pure-cure-akums",
    category: "Pharma Cosmetic & Ayush/HEALTHCARE",
    address: "Plot No.27-30,Sector-8a,Sidcul Haridwar",
    phone: "8755500021",
    description: "Contact: MR. K.D.SHARMA",
    sourceUrl: "local://members-directory/pharma-cosmetic-ayush-healthcare/pure-cure-akums",
  },
  {
    name: "S.K. Herbals India",
    slug: "s-k-herbals-india",
    category: "Pharma Cosmetic & Ayush/HEALTHCARE",
    address: "Plot No.4,Sector-8b,Sidcul Haridwar",
    phone: "8171875656",
    description: "Contact: MR. PRATIK GUPTA",
    sourceUrl: "local://members-directory/pharma-cosmetic-ayush-healthcare/s-k-herbals-india",
  },
  {
    name: "SUDAMA FRAGRANCES",
    slug: "sudama-fragrances",
    category: "Pharma Cosmetic & Ayush/HEALTHCARE",
    address: "PLOT NO-88,SECTOR-6A,SIDCUL HARIDWAR",
    phone: "9027242622",
    description: "Contact: ANKIT MAHESHWARI",
    sourceUrl: "local://members-directory/pharma-cosmetic-ayush-healthcare/sudama-fragrances",
  },
  {
    name: "VEDIKA HERBALS",
    slug: "vedika-herbals",
    category: "Pharma Cosmetic & Ayush/HEALTHCARE",
    address: "PLOT NO.19-20,SECTOR-4,SIDCUL HARIDWAR",
    phone: "7895493333",
    description: "Contact: VIPIN PAL",
    sourceUrl: "local://members-directory/pharma-cosmetic-ayush-healthcare/vedika-herbals",
  },
  {
    name: "WIPRO ENTERPRISES",
    slug: "wipro-enterprises",
    category: "Pharma Cosmetic & Ayush/HEALTHCARE",
    address: "PLOT NO-99-104,SECTOR-6A,SIDCUL HARIDWAR",
    phone: "9997797712",
    description: "Contact: ARVIND CHAUHAN",
    sourceUrl: "local://members-directory/pharma-cosmetic-ayush-healthcare/wipro-enterprises",
  },
  {
    name: "ZENEX ANIMAL HEALTH INDIA PVT.LTD.",
    slug: "zenex-animal-health-india-pvt-ltd",
    category: "Pharma Cosmetic & Ayush/HEALTHCARE",
    address: "PLOT NO-F-1/1,SECTOR-6B,SIDCUL HARIDWAR",
    phone: "9536907737",
    description: "Contact: HEM JOSHI",
    sourceUrl: "local://members-directory/pharma-cosmetic-ayush-healthcare/zenex-animal-health-india-pvt-ltd",
  },
  {
    name: "MCNROE CONSUMER PRODUCTS",
    slug: "mcnroe-consumer-products",
    category: "Pharma Cosmetic & Ayush/HEALTHCARE",
    address: "PLOT NO.46-48,SECTOR-1B,SIDCUL HARIDWAR",
    phone: "9927292372",
    description: "Contact: ARUN SINGH",
    sourceUrl: "local://members-directory/pharma-cosmetic-ayush-healthcare/mcnroe-consumer-products",
  },
  {
    name: "NEEUPURE PHARMA PVT.LTD.",
    slug: "neeupure-pharma-pvt-ltd",
    category: "Pharma Cosmetic & Ayush/HEALTHCARE",
    address: "PLOT NO.222,SECTOR-7,SIDCUL HARIDWAR",
    phone: "9634743705",
    description: "Contact: NIKHIL GOEL",
    sourceUrl: "local://members-directory/pharma-cosmetic-ayush-healthcare/neeupure-pharma-pvt-ltd",
  },
  {
    name: "ANGIA RX LIFE SOLUTION",
    slug: "angia-rx-life-solution",
    category: "Pharma Cosmetic & Ayush/HEALTHCARE",
    address: "RAMNAGAR INDUSTRIAL AREA ROORKEE",
    phone: "7017341383",
    description: "Contact: AJAY JAIN",
    sourceUrl: "local://members-directory/pharma-cosmetic-ayush-healthcare/angia-rx-life-solution",
  },
  {
    name: "KRISHNA ENTERPRISES",
    slug: "krishna-enterprises",
    category: "Pharma Cosmetic & Ayush/HEALTHCARE",
    address: "PLOT NO.46,SECTOR-2,SIDCUL HARIDWAR",
    phone: "9411175899",
    description: "Contact: SUMEET",
    sourceUrl: "local://members-directory/pharma-cosmetic-ayush-healthcare/krishna-enterprises",
  },
  {
    name: "SHIVALIK ENTERPRISES",
    slug: "shivalik-enterprises",
    category: "Pharma Cosmetic & Ayush/HEALTHCARE",
    address: "PLOT NO.16C,IP-2,SALEMPUR MEHDOOD SIDCUL HARIDWAR",
    phone: "7060409061",
    description: "Contact: RAHUL SINGHAL",
    sourceUrl: "local://members-directory/pharma-cosmetic-ayush-healthcare/shivalik-enterprises",
  },
  {
    name: "VYAS PHARMACUETICALS",
    slug: "vyas-pharmacueticals",
    category: "Pharma Cosmetic & Ayush/HEALTHCARE",
    address: "PLOT NO.77,SECTOR-6A,SIDCUL HARIDWAR",
    phone: "9412941526",
    description: "Contact: ASHISH VYAS",
    sourceUrl: "local://members-directory/pharma-cosmetic-ayush-healthcare/vyas-pharmacueticals",
  },
  {
    name: "MOUNTAIN VALLEY SPRINGS INDIA PVT LTD",
    slug: "mountain-valley-springs-india-pvt-ltd",
    category: "Pharma Cosmetic & Ayush/HEALTHCARE",
    address: "PLOT NO-E46,E47 BAHADRABAD",
    phone: "9634434268 / 8791418240",
    description: "Contact: SANJAY JOSHI / VIPIN SHARMA",
    sourceUrl: "local://members-directory/pharma-cosmetic-ayush-healthcare/mountain-valley-springs-india-pvt-ltd",
  },
  {
    name: "Agrawal Drugs Pvt.Ltd.",
    slug: "agrawal-drugs-pvt-ltd",
    category: "Pharma Cosmetic & Ayush/HEALTHCARE",
    address: "Plot No.24,Sector-6B,Sidcul Haridwar",
    phone: "9536384452",
    description: "Contact: Mr.Sumit JI",
    sourceUrl: "local://members-directory/pharma-cosmetic-ayush-healthcare/agrawal-drugs-pvt-ltd",
  },
  {
    name: "Arogya Formulations Pvt.Ltd.",
    slug: "arogya-formulations-pvt-ltd",
    category: "Pharma Cosmetic & Ayush/HEALTHCARE",
    address: "Plot No.76,Sector-6A,Sidcul Haridwar",
    phone: "7060204646",
    description: "Contact: Dr Mohinder Ahuja ji",
    sourceUrl: "local://members-directory/pharma-cosmetic-ayush-healthcare/arogya-formulations-pvt-ltd",
  },
  {
    name: "Biomed Healthcare Products Pvt.Ltd.",
    slug: "biomed-healthcare-products-pvt-ltd",
    category: "Pharma Cosmetic & Ayush/HEALTHCARE",
    address: "Plot No.62-65,Sector-6A,IIE Sidcul Haridwar",
    phone: "8279637611",
    description: "Contact: Mr.Ram Vivek Ji",
    sourceUrl: "local://members-directory/pharma-cosmetic-ayush-healthcare/biomed-healthcare-products-pvt-ltd",
  },
  {
    name: "COSMEDEN Personal Care",
    slug: "cosmeden-personal-care",
    category: "Pharma Cosmetic & Ayush/HEALTHCARE",
    address: "PLOT NO17-,SECTOR-3,SIDCUL HARIDWAR",
    phone: "9720168192",
    description: "Contact: MR.SAURABH GUPTA  Ji",
    sourceUrl: "local://members-directory/pharma-cosmetic-ayush-healthcare/cosmeden-personal-care",
  },
  {
    name: "G.K. Burman Herbals Pvt. Ltd",
    slug: "g-k-burman-herbals-pvt-ltd",
    category: "Pharma Cosmetic & Ayush/HEALTHCARE",
    address: "Plot No.14,Sector-6b,Sidcul Haridwar",
    phone: "81938 12008",
    description: "Contact: Mr.Abhishek Rai Ji",
    sourceUrl: "local://members-directory/pharma-cosmetic-ayush-healthcare/g-k-burman-herbals-pvt-ltd",
  },
  {
    name: "Ginni Filaments Ltd.",
    slug: "ginni-filaments-ltd",
    category: "Pharma Cosmetic & Ayush/HEALTHCARE",
    address: "Plot No.98,Sector-5,Sidcul Haridwar",
    phone: "81712 01821",
    description: "Contact: Mr.V. K. Tripathi Ji",
    sourceUrl: "local://members-directory/pharma-cosmetic-ayush-healthcare/ginni-filaments-ltd",
  },
  {
    name: "JINEKA HEALTHCARE PVT.LTD.",
    slug: "jineka-healthcare-pvt-ltd",
    category: "Pharma Cosmetic & Ayush/HEALTHCARE",
    address: "PLOT NO.555,BEDPURRAILWAY CROSSING,, BYPASS ROORKEE HARIDWAR",
    phone: "98373 59119",
    description: "Contact: Mr.Anil Sharma Ji",
    sourceUrl: "local://members-directory/pharma-cosmetic-ayush-healthcare/jineka-healthcare-pvt-ltd",
  },
  {
    name: "Jocund India Ltd.",
    slug: "jocund-india-ltd",
    category: "Pharma Cosmetic & Ayush/HEALTHCARE",
    address: "Plot No.27-30,Sector-6A,Sidcul Haridwar",
    phone: "7536027497",
    description: "Contact: MR. GURPREET SINGH Ji",
    sourceUrl: "local://members-directory/pharma-cosmetic-ayush-healthcare/jocund-india-ltd",
  },
  {
    name: "Horiba India Pvt. Ltd",
    slug: "horiba-india-pvt-ltd",
    category: "Pharma Cosmetic & Ayush/HEALTHCARE",
    address: "PLOT NO-26,SECTOR-7,SIDCUL HARIDWAR",
    phone: "9927155599",
    description: "Contact: MR.Manoj Ji",
    sourceUrl: "local://members-directory/pharma-cosmetic-ayush-healthcare/horiba-india-pvt-ltd",
  },
  {
    name: "Polymed Polymedicure",
    slug: "polymed-polymedicure",
    category: "Pharma Cosmetic & Ayush/HEALTHCARE",
    address: "Plot.17 Sec-3,SIDCUL",
    phone: "9873237241",
    description: "Contact: BAL KISHAN",
    sourceUrl: "local://members-directory/pharma-cosmetic-ayush-healthcare/polymed-polymedicure",
  },
  {
    name: "ESME Consumer",
    slug: "esme-consumer",
    category: "Pharma Cosmetic & Ayush/HEALTHCARE",
    address: "Plot No.26,Sec-6B,SIDCUL",
    phone: "8171640707",
    description: "Contact: DINESH",
    sourceUrl: "local://members-directory/pharma-cosmetic-ayush-healthcare/esme-consumer",
  },
  {
    name: "SANJIVANI HERBALS",
    slug: "sanjivani-herbals",
    category: "Pharma Cosmetic & Ayush/HEALTHCARE",
    address: "PLOT NO.28,SEC-3 Sidcul Haridwar",
    phone: "9997338292",
    description: "Contact: Mr.AJAY GUPTA Ji",
    sourceUrl: "local://members-directory/pharma-cosmetic-ayush-healthcare/sanjivani-herbals",
  },
  {
    name: "Anamika Herbals",
    slug: "anamika-herbals",
    category: "Pharma Cosmetic & Ayush/HEALTHCARE",
    address: "Plot No.17,Sec-6B Sidcul Haridar",
    phone: "7300709002",
    description: "Contact: Mr.SEEMA AGARWAL Ji",
    sourceUrl: "local://members-directory/pharma-cosmetic-ayush-healthcare/anamika-herbals",
  },
  {
    name: "Medicamen Organics Ltd Unit-2",
    slug: "medicamen-organics-ltd-unit-2",
    category: "Pharma Cosmetic & Ayush/HEALTHCARE",
    address: "Plot No-61 Sec-6A",
    phone: "9045912341",
    description: "Contact: MR.SUNIL JI",
    sourceUrl: "local://members-directory/pharma-cosmetic-ayush-healthcare/medicamen-organics-ltd-unit-2",
  },
  {
    name: "PYRAX INTERNATIONAL",
    slug: "pyrax-international",
    category: "Pharma Cosmetic & Ayush/HEALTHCARE",
    address: "64/A,SUNEHRA ROAD,ADJ,SALEMPUR INDUSTRIAL ESTATE ROORKEE",
    phone: "9412071837",
    description: "Contact: MR.ANURAG GUPTA JI",
    sourceUrl: "local://members-directory/pharma-cosmetic-ayush-healthcare/pyrax-international",
  },
  {
    name: "APCO PHARMA",
    slug: "apco-pharma",
    category: "Pharma Cosmetic & Ayush/HEALTHCARE",
    address: "OLD INDUSTRIAL AREA HARIDWAR",
    phone: "9412074084",
    description: "Contact: MR.PRAKASH SETIA JI",
    sourceUrl: "local://members-directory/pharma-cosmetic-ayush-healthcare/apco-pharma",
  },
  {
    name: "Enviro Analytical Laboratories Llp.",
    slug: "enviro-analytical-laboratories-llp",
    category: "Pharma Cosmetic & Ayush/HEALTHCARE",
    address: "20,Shiv Vihar Near Pace International School,, Sitapur,Jwalapur Haridwar",
    phone: null,
    description: null,
    sourceUrl: "local://members-directory/pharma-cosmetic-ayush-healthcare/enviro-analytical-laboratories-llp",
  },
  {
    name: "Rainbow Packaging Industries",
    slug: "rainbow-packaging-industries",
    category: "Paper & Paper Packaging",
    address: "Plot No.13,Sector-3,Sidcul Haridwar",
    phone: "9760044177",
    description: "Contact: MR.AMIT JALAN",
    sourceUrl: "local://members-directory/paper-paper-packaging/rainbow-packaging-industries",
  },
  {
    name: "Riyansh Packaging",
    slug: "riyansh-packaging",
    category: "Paper & Paper Packaging",
    address: "Khasra No.16,Bhaddarpur Saini,Bahadrabad Haridwar",
    phone: "9837810099",
    description: "Contact: MR. DEEPAK GUPTA",
    sourceUrl: "local://members-directory/paper-paper-packaging/riyansh-packaging",
  },
  {
    name: "Sbj Packaging Industries Pvt.Ltd.",
    slug: "sbj-packaging-industries-pvt-ltd",
    category: "Paper & Paper Packaging",
    address: "Plot No.58-59,Sector-5,IIE Sidcul Haridwar",
    phone: "8979558822",
    description: "Contact: MR. AMAR SINGH",
    sourceUrl: "local://members-directory/paper-paper-packaging/sbj-packaging-industries-pvt-ltd",
  },
  {
    name: "TCPL PACKAGING",
    slug: "tcpl-packaging",
    category: "Paper & Paper Packaging",
    address: "PLOT NO-1-1,SECTOR-6A,SIDCUL HARIDWAR",
    phone: "9720004341",
    description: "Contact: L.K.VIJAYAVRGIYA",
    sourceUrl: "local://members-directory/paper-paper-packaging/tcpl-packaging",
  },
  {
    name: "GULSHAN LAMEE PACK",
    slug: "gulshan-lamee-pack",
    category: "Paper & Paper Packaging",
    address: "PLOT NO.9,SECTOR-1A,SIDCUL HARIDWAR",
    phone: "8445611323",
    description: "Contact: AKSHAY",
    sourceUrl: "local://members-directory/paper-paper-packaging/gulshan-lamee-pack",
  },
  {
    name: "A.P.Print 'N' Pack Pvt. Ltd",
    slug: "a-p-print-n-pack-pvt-ltd",
    category: "Paper & Paper Packaging",
    address: "Plot No.19,Sector-2,IIE Sidcul Haridwar",
    phone: "93584 16644",
    description: "Contact: Mr.Manoj Ji",
    sourceUrl: "local://members-directory/paper-paper-packaging/a-p-print-n-pack-pvt-ltd",
  },
  {
    name: "AADHARSHREE PAPER MILL Pvt. Ltd",
    slug: "aadharshree-paper-mill-pvt-ltd",
    category: "Paper & Paper Packaging",
    address: "RUDRAPUR, Uttarakhand",
    phone: "96346 10379",
    description: "Contact: Mr.Manoj Ji",
    sourceUrl: "local://members-directory/paper-paper-packaging/aadharshree-paper-mill-pvt-ltd",
  },
  {
    name: "Ak Bakelite India",
    slug: "ak-bakelite-india",
    category: "Paper & Paper Packaging",
    address: "Plot No.53,Sector-2,Sidcul Haridwar",
    phone: "95404 76145",
    description: "Contact: Mr.Mahesh JI",
    sourceUrl: "local://members-directory/paper-paper-packaging/ak-bakelite-india",
  },
  {
    name: "Arvind Chemi Synthetics Pvt.Ltd.",
    slug: "arvind-chemi-synthetics-pvt-ltd",
    category: "Paper & Paper Packaging",
    address: "Plot No.35-36,Sector-3a,IIE Sidcul Haridwar",
    phone: "9910696137",
    description: "Contact: Mr.Keshav Kumar Sekhri Ji",
    sourceUrl: "local://members-directory/paper-paper-packaging/arvind-chemi-synthetics-pvt-ltd",
  },
  {
    name: "Bk Print and Pack",
    slug: "bk-print-and-pack",
    category: "Paper & Paper Packaging",
    address: "Plot No.26,Sector-8a,Sidcul Haridwar",
    phone: "9412999003",
    description: "Contact: Mr.Sandeep Singla Ji",
    sourceUrl: "local://members-directory/paper-paper-packaging/bk-print-and-pack",
  },
  {
    name: "Kamipro",
    slug: "kamipro",
    category: "Paper & Paper Packaging",
    address: "Khasra No.68,Lakesri,Sikandarpur,Bhainwal, Bhagwanpur Haridwar",
    phone: "81717 35753",
    description: "Contact: Mr.R.K.SINGH Ji",
    sourceUrl: "local://members-directory/paper-paper-packaging/kamipro",
  },
  {
    name: "Square Vision India Pvt Ltd",
    slug: "square-vision-india-pvt-ltd",
    category: "Paper & Paper Packaging",
    address: "Plot No-28,29 Sec-4 Sidcul Haridwar",
    phone: "7300777797",
    description: "Contact: Mr.SUSHIL DIXIT Ji",
    sourceUrl: "local://members-directory/paper-paper-packaging/square-vision-india-pvt-ltd",
  },
  {
    name: "Safeguard Industries",
    slug: "safeguard-industries",
    category: "Building Materials & Others Chemicals",
    address: "Plot No.30,Sector-Iidc,Sidcul Haridwar",
    phone: "7017448913",
    description: "Contact: MR. RAJ ARORA",
    sourceUrl: "local://members-directory/building-materials-others-chemicals/safeguard-industries",
  },
  {
    name: "Spemtt Lifesciences",
    slug: "spemtt-lifesciences",
    category: "Building Materials & Others Chemicals",
    address: "C-44,Shivalik Nagar Bhel,Ranipur Haridwar",
    phone: "9719976556",
    description: "Contact: MR. NAVNEET SHARMA",
    sourceUrl: "local://members-directory/building-materials-others-chemicals/spemtt-lifesciences",
  },
  {
    name: "SWASTI STRUCTURE & CONCRETES",
    slug: "swasti-structure-concretes",
    category: "Building Materials & Others Chemicals",
    address: "IBRAHIMPUR BAHADRABAD HARIDWAR",
    phone: "9719004013",
    description: "Contact: PIYUSH JAIN",
    sourceUrl: "local://members-directory/building-materials-others-chemicals/swasti-structure-concretes",
  },
  {
    name: "TEHRI IRON & STEEL INDUSTRIES",
    slug: "tehri-iron-steel-industries",
    category: "Building Materials & Others Chemicals",
    address: "KH.NO.314-332,RAJPUR,BHAGWANPUR",
    phone: "9837051944",
    description: "Contact: VIKAS GOYAL",
    sourceUrl: "local://members-directory/building-materials-others-chemicals/tehri-iron-steel-industries",
  },
  {
    name: "VIKAS INDUSTRIES",
    slug: "vikas-industries",
    category: "Building Materials & Others Chemicals",
    address: "D-5,OLD INDUSTRIAL AREA HARIDWAR",
    phone: "9837044984",
    description: "Contact: VIKAS GOYAL",
    sourceUrl: "local://members-directory/building-materials-others-chemicals/vikas-industries",
  },
  {
    name: "HARSHITH MANUFACTURING PVT.LTD.",
    slug: "harshith-manufacturing-pvt-ltd",
    category: "Building Materials & Others Chemicals",
    address: "KH.NO.150,IP-4,BEGAMPUR BAHADRABAD",
    phone: "9897770289",
    description: "Contact: AMAN GUPTA",
    sourceUrl: "local://members-directory/building-materials-others-chemicals/harshith-manufacturing-pvt-ltd",
  },
  {
    name: "Asahi India Glass Ltd.",
    slug: "asahi-india-glass-ltd",
    category: "Building Materials & Others Chemicals",
    address: "Plot - A, B & B-1, AIS Industrial Estate Village Latherdeva Hoon MangularJhabrera, Tehsil, Road, PO:, Jhabrera, Roorkee, Uttarakhand",
    phone: "70550 00900",
    description: "Contact: Mr.Ranbir Negi Ji",
    sourceUrl: "local://members-directory/building-materials-others-chemicals/asahi-india-glass-ltd",
  },
  {
    name: "Forace Speciality Chem Pvt.Ltd.",
    slug: "forace-speciality-chem-pvt-ltd",
    category: "Building Materials & Others Chemicals",
    address: "10km Stone, Delhi-Haridwar Road, Bahadrabad Haridwar",
    phone: "97567 09211",
    description: "Contact: Mr.Tarun Chauhan Ji",
    sourceUrl: "local://members-directory/building-materials-others-chemicals/forace-speciality-chem-pvt-ltd",
  },
  {
    name: "Gold Plus Glass Industry Ltd.",
    slug: "gold-plus-glass-industry-ltd",
    category: "Building Materials & Others Chemicals",
    address: "Vill- Thithola,Roorkee -Laksar Road,Roorkee, Haridwar",
    phone: "89790 00408",
    description: "Contact: Mr.Surendra Singh Ji",
    sourceUrl: "local://members-directory/building-materials-others-chemicals/gold-plus-glass-industry-ltd",
  },
  {
    name: "Ideal Elastomers",
    slug: "ideal-elastomers",
    category: "Building Materials & Others Chemicals",
    address: "Plot No.16f,Industrial Park-2,Salempur, Mehdood,Sidcul Haridwar",
    phone: "8126445666",
    description: "Contact: MR. SAMSHEER Ji",
    sourceUrl: "local://members-directory/building-materials-others-chemicals/ideal-elastomers",
  },
  {
    name: "Indian Rubber Products",
    slug: "indian-rubber-products",
    category: "Building Materials & Others Chemicals",
    address: "E 67-69/74-76, Industrial Area, SIDCUL,Haridwar",
    phone: null,
    description: null,
    sourceUrl: "local://members-directory/building-materials-others-chemicals/indian-rubber-products",
  },
  {
    name: "Speedcrafts Ltd",
    slug: "speedcrafts-ltd",
    category: "Building Materials & Others Chemicals",
    address: "Plot No-1A,Sec-7,SIDCUL",
    phone: "7903622969/8171155333",
    description: "Contact: LALIT MORE/MANDEEP",
    sourceUrl: "local://members-directory/building-materials-others-chemicals/speedcrafts-ltd",
  },
  {
    name: "KIRBY",
    slug: "kirby",
    category: "Building Materials & Others Chemicals",
    address: "PLOT NO-2 SEC-11 SIDCUL HARIDWAR",
    phone: "9719266644",
    description: "Contact: DHIRENDRA CHAUHAN",
    sourceUrl: "local://members-directory/building-materials-others-chemicals/kirby",
  },
  {
    name: "M/S DIVYA SOAPS Pvt.Ltd",
    slug: "m-s-divya-soaps-pvt-ltd",
    category: "Building Materials & Others Chemicals",
    address: "PLOT NO-30,F SEC-11 SIDCUL HARIDWAR",
    phone: "9719900368",
    description: "Contact: Mr.UMESH Kashyap JI",
    sourceUrl: "local://members-directory/building-materials-others-chemicals/m-s-divya-soaps-pvt-ltd",
  },
  {
    name: "REDSUN PAINTS",
    slug: "redsun-paints",
    category: "Building Materials & Others Chemicals",
    address: "KH.NO.286,GADOWALI,BHADARPUR JATT",
    phone: "7417529604/8449736736",
    description: "Contact: MR.PRADEEP SINGH & Mr.AKASH WALIA JI",
    sourceUrl: "local://members-directory/building-materials-others-chemicals/redsun-paints",
  },
  {
    name: "JET STAR ENGGINEERING",
    slug: "jet-star-enggineering",
    category: "Building Materials & Others Chemicals",
    address: "PLOT NO.75,SEC-IIDC,",
    phone: "8194010206",
    description: "Contact: MR.JAYANT PANT JI",
    sourceUrl: "local://members-directory/building-materials-others-chemicals/jet-star-enggineering",
  },
  {
    name: "MEDICAL POLLUTION CONTROL COMMITTEE",
    slug: "medical-pollution-control-committee",
    category: "Service Provider",
    address: "SAHASTRADHARA ROAD,DEHRADUN",
    phone: "9084155469",
    description: "Contact: MR. JAI SHARMA",
    sourceUrl: "local://members-directory/service-provider/medical-pollution-control-committee",
  },
  {
    name: "Ovolo It Building  Solutions",
    slug: "ovolo-it-building-solutions",
    category: "Service Provider",
    address: "Iit Roorkee Haridwar",
    phone: "9997008775",
    description: "Contact: MR. SANJAY PAL",
    sourceUrl: "local://members-directory/service-provider/ovolo-it-building-solutions",
  },
  {
    name: "Phonics Group of Institution",
    slug: "phonics-group-of-institution",
    category: "Service Provider",
    address: "Imli Khera Dharampur,12th,Milestone,Highway, Bhagwanpur",
    phone: "9756813333",
    description: "Contact: MR. RIPESH PANT",
    sourceUrl: "local://members-directory/service-provider/phonics-group-of-institution",
  },
  {
    name: "Roopak Gupta",
    slug: "roopak-gupta",
    category: "Service Provider",
    address: "Shivalik Nagar Bhel Ranipur Haridwar",
    phone: "8859144844",
    description: "Contact: ADV. ROOPAK GUPTA",
    sourceUrl: "local://members-directory/service-provider/roopak-gupta",
  },
  {
    name: "Roorkee Small Scale Ind. Association",
    slug: "roorkee-small-scale-ind-association",
    category: "Service Provider",
    address: "Ramnagar Industrial Area,, Roorkee ( Haridwar)",
    phone: "9897152595",
    description: "Contact: MR. MUKUL GARG",
    sourceUrl: "local://members-directory/service-provider/roorkee-small-scale-ind-association",
  },
  {
    name: "Samrat Security Services",
    slug: "samrat-security-services",
    category: "Service Provider",
    address: "Old Industrial Area Haridwar",
    phone: "9412957114",
    description: "Contact: MR. RAJESH SHARMA",
    sourceUrl: "local://members-directory/service-provider/samrat-security-services",
  },
  {
    name: "NARUMA INDUSTRIES",
    slug: "naruma-industries",
    category: "Service Provider",
    address: "JAGJEETPUR KANKHAL",
    phone: "9766543977",
    description: "Contact: MR. VANSHAJ GUPTA",
    sourceUrl: "local://members-directory/service-provider/naruma-industries",
  },
  {
    name: "SAN SERVICES",
    slug: "san-services",
    category: "Service Provider",
    address: "SHIVALIK NAGAR BHEL HARIDWAR",
    phone: "7860600170",
    description: "Contact: PRAVESH SHARMA",
    sourceUrl: "local://members-directory/service-provider/san-services",
  },
  {
    name: "TEERHANKAR MAHAVEER INSTITUTE OF MANAGEMENT",
    slug: "teerhankar-mahaveer-institute-of-management",
    category: "Service Provider",
    address: "MURADABAD",
    phone: "95209 66416",
    description: "Contact: DR. DILIP DUTTA",
    sourceUrl: "local://members-directory/service-provider/teerhankar-mahaveer-institute-of-management",
  },
  {
    name: "HARIDWAR UNIVERSITY",
    slug: "haridwar-university",
    category: "Service Provider",
    address: "CANAL ROAD,BAHUHARI ROORKEE",
    phone: "9897053399",
    description: "Contact: S.K.GUPTA",
    sourceUrl: "local://members-directory/service-provider/haridwar-university",
  },
  {
    name: "Bhavani Engineering",
    slug: "bhavani-engineering",
    category: "Service Provider",
    address: "Plot No.93,Sector-7,Sidcul Haridwar",
    phone: "93190 80827",
    description: "Contact: Mr.Prakesh Rathor Ji",
    sourceUrl: "local://members-directory/service-provider/bhavani-engineering",
  },
  {
    name: "Lohia Health Pvt.Ltd.",
    slug: "lohia-health-pvt-ltd",
    category: "Service Provider",
    address: "Ekaanta,Niranjani Akhara Marg,, Devpura,Haridwar",
    phone: "93586 31551",
    description: "Contact: Mr.Praveen Sharma Ji",
    sourceUrl: "local://members-directory/service-provider/lohia-health-pvt-ltd",
  },
  {
    name: "Advocate",
    slug: "advocate",
    category: "Service Provider",
    address: "Ranipur mode,Haridwar",
    phone: "94120 70786",
    description: "Contact: Mr.Lalit Sachdeva Ji",
    sourceUrl: "local://members-directory/service-provider/advocate",
  },
  {
    name: "Agromech Engineers",
    slug: "agromech-engineers",
    category: "Service Provider",
    address: "Near Bharat Petrol Pump,Haridwar Road,Bahadrabad, Haridwar",
    phone: "98970 98951",
    description: "Contact: Mr.Jatin Aggarwal Ji",
    sourceUrl: "local://members-directory/service-provider/agromech-engineers",
  },
  {
    name: "Mr.Jagdish Lal Pahwa Ji",
    slug: "mr-jagdish-lal-pahwa-ji",
    category: "Service Provider",
    address: "Ranipur mode,Haridwar",
    phone: "78189 50620",
    description: "Contact: Mr.Jagdish Lal Pahwa Ji",
    sourceUrl: "local://members-directory/service-provider/mr-jagdish-lal-pahwa-ji",
  },
  {
    name: "COER University",
    slug: "coer-university",
    category: "Service Provider",
    address: "7th km of the Roorkee–Haridwar Highway (NH-58), near Belda Village, Vardhmanpuram, Roorkee–247667, Distt. Haridwar, Uttarakhand,",
    phone: "8755352001",
    description: "Contact: Mrs. Mamta Singh",
    sourceUrl: "local://members-directory/service-provider/coer-university",
  },
  {
    name: "ENVIRO CONNECT",
    slug: "enviro-connect",
    category: "Service Provider",
    address: "46, First Floor, City Pride Complex, Civil Lines, Roorkee, Dist: Haridwar, Uttarakhand",
    phone: "7906100946",
    description: "Contact: MR.AKSHAT BHATEJA",
    sourceUrl: "local://members-directory/service-provider/enviro-connect",
  },
  {
    name: "India Factoring and Finance Solution Pvt.Ltd.",
    slug: "india-factoring-and-finance-solution-pvt-ltd",
    category: "Service Provider",
    address: "Unit-808-809,India Factoring Tolstoy Marg,, Prakashdee,Building Barakhamba Road,New Delhi",
    phone: null,
    description: null,
    sourceUrl: "local://members-directory/service-provider/india-factoring-and-finance-solution-pvt-ltd",
  },
  {
    name: "Prachi Leather",
    slug: "prachi-leather",
    category: "Service Provider",
    address: "Plot No.18,19 Sec-4,SIDCUL",
    phone: "9675734427/8090054551",
    description: "Contact: AJEET SAXENA",
    sourceUrl: "local://members-directory/service-provider/prachi-leather",
  },
  {
    name: "Rubico Pvt.ltd",
    slug: "rubico-pvt-ltd",
    category: "Service Provider",
    address: "Plot No-19 Sec-12 Sidcul Haridwar",
    phone: "8532967097",
    description: "Contact: KRISHNA PANT",
    sourceUrl: "local://members-directory/service-provider/rubico-pvt-ltd",
  },
  {
    name: "East West Engineering co.",
    slug: "east-west-engineering-co",
    category: "Service Provider",
    address: "Plot No.20,Sec-1B HARIDWAR,UTTARAKHAND",
    phone: "9810054835",
    description: "Contact: Mr.PAWAN GUPTA Ji",
    sourceUrl: "local://members-directory/service-provider/east-west-engineering-co",
  },
  {
    name: "FIRE SAFETY DEVICES PVT.LTD.",
    slug: "fire-safety-devices-pvt-ltd",
    category: "Service Provider",
    address: "PLOT NO.19-20,SEC-3A",
    phone: "8057909210",
    description: "Contact: Mr.JAI SINGH Ji",
    sourceUrl: "local://members-directory/service-provider/fire-safety-devices-pvt-ltd",
  },
  {
    name: "BAGGA INDUSTRIES",
    slug: "bagga-industries",
    category: "Service Provider",
    address: "PLOT NO.128,SECTOR-6A,SIDCUL HARIDWAR",
    phone: "9927744711",
    description: "Contact: Mr.HARDEEP BAGGA Ji",
    sourceUrl: "local://members-directory/service-provider/bagga-industries",
  },
  {
    name: "CA AMIT",
    slug: "ca-amit",
    category: "Service Provider",
    address: "ROORKEE HARIDWAR",
    phone: "9897999967",
    description: "Contact: MR.AMIT SINGH Ji",
    sourceUrl: "local://members-directory/service-provider/ca-amit",
  },
  {
    name: "HOTEL GARDENIA",
    slug: "hotel-gardenia",
    category: "Service Provider",
    address: "Sidcul haridwar",
    phone: "9897061303",
    description: "Contact: Mr.SANJEEV GUPTA Ji",
    sourceUrl: "local://members-directory/service-provider/hotel-gardenia",
  },
  {
    name: "Enntee International Ltd",
    slug: "enntee-international-ltd",
    category: "Service Provider",
    address: "Plot No.9 Sec-3 Sidcul Haridwar",
    phone: "9760327452",
    description: "Contact: Mr.A.K.SHARMA Ji",
    sourceUrl: "local://members-directory/service-provider/enntee-international-ltd",
  },
  {
    name: "CRIMPTECH SOLUTION MFG.",
    slug: "crimptech-solution-mfg",
    category: "Service Provider",
    address: "PLOT NO-5,SECTOR-IIDC,SIDCUL",
    phone: "9319059893",
    description: "Contact: MR.ISHWAR JI",
    sourceUrl: "local://members-directory/service-provider/crimptech-solution-mfg",
  },
  {
    name: "AQUA SOFT SAFE DRINKING WATER",
    slug: "aqua-soft-safe-drinking-water",
    category: "Service Provider",
    address: "PLOT NO-E38 BAHADRABAD",
    phone: "99272 20099",
    description: "Contact: MR.R.SHARMA JI",
    sourceUrl: "local://members-directory/service-provider/aqua-soft-safe-drinking-water",
  },
  {
    name: "STEELWELL ENGINEERING & SERVICES",
    slug: "steelwell-engineering-services",
    category: "Service Provider",
    address: "PLOT NO-D28 BAHADRABAD",
    phone: "8266006699",
    description: "Contact: MR.MANOJ MEHRA JI",
    sourceUrl: "local://members-directory/service-provider/steelwell-engineering-services",
  },
  {
    name: "AVANTI BUFA PVT.LTD.",
    slug: "avanti-bufa-pvt-ltd",
    category: "Service Provider",
    address: "Kh No-235-236, Roorkee Raipur Industrial Estate, Bhagwanpur, Haridwar",
    phone: "9455617433",
    description: "Contact: MR.DEEP MANI JI",
    sourceUrl: "local://members-directory/service-provider/avanti-bufa-pvt-ltd",
  },
  {
    name: "Marico Nautical Collection",
    slug: "marico-nautical-collection",
    category: "Service Provider",
    address: "223/1A, Mirror Touch Glass House, 1st Floor,, Sheikhpuri, Roorkee, Uttarakhand",
    phone: "9997449032",
    description: "Contact: MR.RIZWAN ALI JI",
    sourceUrl: "local://members-directory/service-provider/marico-nautical-collection",
  },
  {
    name: "THE WESTERN PRECISION INSTRUMENTS EMPORIUM",
    slug: "the-western-precision-instruments-emporium",
    category: "Service Provider",
    address: "PLOT NO. 9-11,INDUSTRIAL ESTATE,RAMNAGAR ROORKEE",
    phone: "9997026679",
    description: "Contact: MR.SUDHANSHU KAPOOR JI",
    sourceUrl: "local://members-directory/service-provider/the-western-precision-instruments-emporium",
  },
  {
    name: "CLASSIC DECORATOR",
    slug: "classic-decorator",
    category: "Service Provider",
    address: "SALEMPUR INDUSTRIAL ESTATE ROORKEE",
    phone: "9897277148",
    description: "Contact: MR.JASWANT SINGH JI",
    sourceUrl: "local://members-directory/service-provider/classic-decorator",
  },
  {
    name: "Uttarakhand Drugs Ayush & Naturopathy",
    slug: "uttarakhand-drugs-ayush-naturopathy",
    category: "Service Provider",
    address: "C/o Arogya Formulations P Ltd, Sidcul, Haridwar",
    phone: "7060204646",
    description: "Contact: DR. MOHINDRA AHUJA JI",
    sourceUrl: "local://members-directory/service-provider/uttarakhand-drugs-ayush-naturopathy",
  },
  {
    name: "Drug Manufacturers Association Uttarakhand",
    slug: "drug-manufacturers-association-uttarakhand",
    category: "Service Provider",
    address: "E-18,Selaqui Industrial Area Selaqui,Dehradun",
    phone: null,
    description: null,
    sourceUrl: "local://members-directory/service-provider/drug-manufacturers-association-uttarakhand",
  },
  {
    name: "Tomar Protection Services Pvt.Ltd.",
    slug: "tomar-protection-services-pvt-ltd",
    category: "Service Provider",
    address: "Mb-37, Indralok Colony,Sidcul Haridwar",
    phone: "9410905535",
    description: "Contact: MR.N.S.TOMAR JI",
    sourceUrl: "local://members-directory/service-provider/tomar-protection-services-pvt-ltd",
  },
  {
    name: "Mahavir Agro Oils",
    slug: "mahavir-agro-oils",
    category: "Food Processing",
    address: "E-61,Industrial Area Haridwar",
    phone: "9917490000",
    description: "Contact: MR. HARSHIT MALHOTRA",
    sourceUrl: "local://members-directory/food-processing/mahavir-agro-oils",
  },
  {
    name: "Sagar Pulp and Paper Mills",
    slug: "sagar-pulp-and-paper-mills",
    category: "Food Processing",
    address: "Khasra No-14/1,Manglore Deoband Road, Manglore Tahshil Roorkee",
    phone: "9719412661",
    description: "Contact: MR. ANIL TYAGI",
    sourceUrl: "local://members-directory/food-processing/sagar-pulp-and-paper-mills",
  },
  {
    name: "SRINITHI INDUSTRIES",
    slug: "srinithi-industries",
    category: "Food Processing",
    address: "D-10C,SECTOR-1,GROWTH CENER SIGADDI,KOTDWAR",
    phone: "9358220758",
    description: "Contact: RANJEET TIBREWAL",
    sourceUrl: "local://members-directory/food-processing/srinithi-industries",
  },
  {
    name: "SURYA PROCESSED FOOD PVT.LTD.",
    slug: "surya-processed-food-pvt-ltd",
    category: "Food Processing",
    address: "PLOT NO-5,SECTOR-11,SIDCUL HARIDWAR",
    phone: "9720101807",
    description: "Contact: K.C.GUPTA",
    sourceUrl: "local://members-directory/food-processing/surya-processed-food-pvt-ltd",
  },
  {
    name: "APIS INDIA LTD.",
    slug: "apis-india-ltd",
    category: "Food Processing",
    address: "KH.NO-66-72,PEERPURA,ROAD MANGLORE ROORKEE",
    phone: "9012966584",
    description: "Contact: NISHCHAL",
    sourceUrl: "local://members-directory/food-processing/apis-india-ltd",
  },
  {
    name: "ARHAM SUDH WATER & Metals Pvt Ltd",
    slug: "arham-sudh-water-metals-pvt-ltd",
    category: "Food Processing",
    address: "PLOT NO-122,SECTOR-6A,SIDCUL HARIDWAR",
    phone: "94563 81911",
    description: "Contact: R. C. Sharma JI",
    sourceUrl: "local://members-directory/food-processing/arham-sudh-water-metals-pvt-ltd",
  },
  {
    name: "I.T.C LIMITED",
    slug: "i-t-c-limited",
    category: "Food Processing",
    address: "PLOT NO-37, SEC-11 SIDCUL HARIDWAR",
    phone: "8938807810",
    description: "Contact: ALTAF HUSSAIN",
    sourceUrl: "local://members-directory/food-processing/i-t-c-limited",
  },
  {
    name: "Matins Tech Packs",
    slug: "matins-tech-packs",
    category: "Plastic & Plastic Packaging",
    address: "Plot No.10,Sector-5,Sidcul Haridwar",
    phone: "9810121663",
    description: "Contact: MR. KULBHUSHAN SRIDHAR",
    sourceUrl: "local://members-directory/plastic-plastic-packaging/matins-tech-packs",
  },
  {
    name: "Montex Pen Industries",
    slug: "montex-pen-industries",
    category: "Plastic & Plastic Packaging",
    address: "Plot No.10,Sector-6a,IIE Sidcul Haridwar",
    phone: "9917144433",
    description: "Contact: MR. ANUJ",
    sourceUrl: "local://members-directory/plastic-plastic-packaging/montex-pen-industries",
  },
  {
    name: "Navyug Polystock Centre Pvt.Ltd.",
    slug: "navyug-polystock-centre-pvt-ltd",
    category: "Plastic & Plastic Packaging",
    address: "Khasra No.1828,Block-A,Salempur Mehdood, Bahadrabad Haridwar",
    phone: "9368778484",
    description: "Contact: MR. SANJAY BHARTIA",
    sourceUrl: "local://members-directory/plastic-plastic-packaging/navyug-polystock-centre-pvt-ltd",
  },
  {
    name: "Om Products",
    slug: "om-products",
    category: "Plastic & Plastic Packaging",
    address: "Plot No.33,Sector-2,IIE Sidcul Haridwar",
    phone: "9837037782",
    description: "Contact: MR. SATYENDRA GUPTA",
    sourceUrl: "local://members-directory/plastic-plastic-packaging/om-products",
  },
  {
    name: "Om Tech Containers",
    slug: "om-tech-containers",
    category: "Plastic & Plastic Packaging",
    address: "Plot No.23,Sector-11,Sidcul Haridwar",
    phone: "9837095300",
    description: "Contact: MR. ASHWANI KHURANA",
    sourceUrl: "local://members-directory/plastic-plastic-packaging/om-tech-containers",
  },
  {
    name: "OMEGA PRINT O PACK",
    slug: "omega-print-o-pack",
    category: "Plastic & Plastic Packaging",
    address: "PLOT NO-133,SECOR-6A,SIDCUL",
    phone: "9997030304",
    description: "Contact: MR. SANDEEP JAIN",
    sourceUrl: "local://members-directory/plastic-plastic-packaging/omega-print-o-pack",
  },
  {
    name: "Penta Latex Llp",
    slug: "penta-latex-llp",
    category: "Plastic & Plastic Packaging",
    address: "Plot No.49-50,Sector-2,IIE Sidcul Haridwar",
    phone: "8126436869",
    description: "Contact: MR. MAHENDRA DHAKAD",
    sourceUrl: "local://members-directory/plastic-plastic-packaging/penta-latex-llp",
  },
  {
    name: "Pioneer Industries",
    slug: "pioneer-industries",
    category: "Plastic & Plastic Packaging",
    address: "Plot No.48,Sector-2,IIE Sidcul Haridwar",
    phone: "9359525952",
    description: "Contact: MR. SUBHASH KANSAL",
    sourceUrl: "local://members-directory/plastic-plastic-packaging/pioneer-industries",
  },
  {
    name: "Polyflex International",
    slug: "polyflex-international",
    category: "Plastic & Plastic Packaging",
    address: "Plot No.22,Sector-3,Sidcul Haridwar",
    phone: "9319040076",
    description: "Contact: MR. A MANSOORI",
    sourceUrl: "local://members-directory/plastic-plastic-packaging/polyflex-international",
  },
  {
    name: "Prince Pipe & Fittings Ltd.",
    slug: "prince-pipe-fittings-ltd",
    category: "Plastic & Plastic Packaging",
    address: "Ip-2,Salempur Mehdood Haridwar",
    phone: "8979259407",
    description: "Contact: MR. SANJEEV",
    sourceUrl: "local://members-directory/plastic-plastic-packaging/prince-pipe-fittings-ltd",
  },
  {
    name: "RADHEY RADHEY INDUSTRIES",
    slug: "radhey-radhey-industries",
    category: "Plastic & Plastic Packaging",
    address: "PLOT NO.30C,SECTOR-8B,IIE,, SIDCUL HARIDWAR",
    phone: "9412074363",
    description: "Contact: MR. MALHOTRA",
    sourceUrl: "local://members-directory/plastic-plastic-packaging/radhey-radhey-industries",
  },
  {
    name: "Royal Shine Plastic Co.",
    slug: "royal-shine-plastic-co",
    category: "Plastic & Plastic Packaging",
    address: "Plot No.54-55,Sector-2,Sidcul Haridwar",
    phone: "9312622228",
    description: "Contact: MR. VINAY SHUKLA",
    sourceUrl: "local://members-directory/plastic-plastic-packaging/royal-shine-plastic-co",
  },
  {
    name: "Shreeji Propack Pvt.Ltd.",
    slug: "shreeji-propack-pvt-ltd",
    category: "Plastic & Plastic Packaging",
    address: "Plot No.5,Sector-1a,IIE Sidcul Haridwar",
    phone: "9456447988",
    description: "Contact: MR. MOHIT",
    sourceUrl: "local://members-directory/plastic-plastic-packaging/shreeji-propack-pvt-ltd",
  },
  {
    name: "TPAC PACKAGING",
    slug: "tpac-packaging",
    category: "Plastic & Plastic Packaging",
    address: "PLOT NO.6-7,SECTOR-2,SIDCUL HARIDWAR",
    phone: "9359932666",
    description: "Contact: RAVINDRA KUMAR",
    sourceUrl: "local://members-directory/plastic-plastic-packaging/tpac-packaging",
  },
  {
    name: "ADVANCE POLYPACKAGING COMPANY",
    slug: "advance-polypackaging-company",
    category: "Plastic & Plastic Packaging",
    address: "PLOT NO.26,SECTOR-11,SIDCUL HARIDWAR",
    phone: "9720889180",
    description: "Contact: SAMEER GUPTA",
    sourceUrl: "local://members-directory/plastic-plastic-packaging/advance-polypackaging-company",
  },
  {
    name: "ULTRA CRAFT MOULDER",
    slug: "ultra-craft-moulder",
    category: "Plastic & Plastic Packaging",
    address: "ROHALKI ROAD BAHADRABAD HARIDWAR",
    phone: "7351595555",
    description: "Contact: MANMEET KAUR",
    sourceUrl: "local://members-directory/plastic-plastic-packaging/ultra-craft-moulder",
  },
  {
    name: "VANDHANA POLY PLAST",
    slug: "vandhana-poly-plast",
    category: "Plastic & Plastic Packaging",
    address: "PLOT NO.113,SE TOR-6A,SIDCUL HARIDWAR",
    phone: "9897879637",
    description: "Contact: S.S.GUPTA",
    sourceUrl: "local://members-directory/plastic-plastic-packaging/vandhana-poly-plast",
  },
  {
    name: "BABRI POLYPET PVT.LTD.",
    slug: "babri-polypet-pvt-ltd",
    category: "Plastic & Plastic Packaging",
    address: "PLOT NO.71-74,SECTOR-7,SIDCUL HARIDWAR",
    phone: "8126150213",
    description: "Contact: PAWAN SHARMA",
    sourceUrl: "local://members-directory/plastic-plastic-packaging/babri-polypet-pvt-ltd",
  },
  {
    name: "HANSA POLYPACK",
    slug: "hansa-polypack",
    category: "Plastic & Plastic Packaging",
    address: "J-207,SHIVALIK NAGAR BHEL ,HARIDWAR",
    phone: "9319967675",
    description: "Contact: SATYA",
    sourceUrl: "local://members-directory/plastic-plastic-packaging/hansa-polypack",
  },
  {
    name: "BION PLASTIC",
    slug: "bion-plastic",
    category: "Plastic & Plastic Packaging",
    address: "PLOT NO.90-91,SECTOR-IIDC,SIDCUL HARIDWAR",
    phone: "9792887111",
    description: "Contact: HARSH VERMA",
    sourceUrl: "local://members-directory/plastic-plastic-packaging/bion-plastic",
  },
  {
    name: "AUTOMAT IRRIGATION",
    slug: "automat-irrigation",
    category: "Plastic & Plastic Packaging",
    address: "PLOT NO-94,SECTOR-6A,SIDCUL HARIDWAR",
    phone: "9997599444/997206069",
    description: "Contact: MINAAZ KAMAAL/NITIN GUPTA",
    sourceUrl: "local://members-directory/plastic-plastic-packaging/automat-irrigation",
  },
  {
    name: "LOGIC FLAME INDIA PVT.LTD.",
    slug: "logic-flame-india-pvt-ltd",
    category: "Plastic & Plastic Packaging",
    address: "D-25A,Sigaddi Growth Centre, Kotdwar",
    phone: "9911412308",
    description: "Contact: CA.ASHUTOSH PANDEY",
    sourceUrl: "local://members-directory/plastic-plastic-packaging/logic-flame-india-pvt-ltd",
  },
  {
    name: "Delhi Control Devices Pvt.Ltd.",
    slug: "delhi-control-devices-pvt-ltd",
    category: "Plastic & Plastic Packaging",
    address: "Plot No.25,Sector-2,Iie Sidcul Haridwar",
    phone: "97593 75800",
    description: "Contact: Mr.Gaurav Ji",
    sourceUrl: "local://members-directory/plastic-plastic-packaging/delhi-control-devices-pvt-ltd",
  },
  {
    name: "DEEP PACKAGING",
    slug: "deep-packaging",
    category: "Plastic & Plastic Packaging",
    address: "PLOT NO-30-SECTOR-5,SIDCUL HARIDWAR",
    phone: "9759759900",
    description: "Contact: Mr.L.N Sharma",
    sourceUrl: "local://members-directory/plastic-plastic-packaging/deep-packaging",
  },
  {
    name: "Creative PlastoPack",
    slug: "creative-plastopack",
    category: "Plastic & Plastic Packaging",
    address: "Plot No.5,Sector-3,Sidcul Haridwar",
    phone: "80063 66665",
    description: "Contact: Mr.R.K Tyagi Ji",
    sourceUrl: "local://members-directory/plastic-plastic-packaging/creative-plastopack",
  },
  {
    name: "Arun Plasto Moulders India Pvt.Ltd.",
    slug: "arun-plasto-moulders-india-pvt-ltd",
    category: "Plastic & Plastic Packaging",
    address: "Plot No.4,Sector-1A,Sidcul Haridwar",
    phone: "7520006212",
    description: "Contact: Ms.Mamta Senger Ji",
    sourceUrl: "local://members-directory/plastic-plastic-packaging/arun-plasto-moulders-india-pvt-ltd",
  },
  {
    name: "Aroson Plastics Pvt.Ltd.",
    slug: "aroson-plastics-pvt-ltd",
    category: "Plastic & Plastic Packaging",
    address: "D-37,Industrial Area Bahadrabad, Haridwar",
    phone: "9910398887",
    description: "Contact: TRILOKCHAND SINGH",
    sourceUrl: "local://members-directory/plastic-plastic-packaging/aroson-plastics-pvt-ltd",
  },
  {
    name: "Excel Pack Pvt.Ltd.",
    slug: "excel-pack-pvt-ltd",
    category: "Plastic & Plastic Packaging",
    address: "Plot No.8,Sector-4,IIE Sidcul Haridwar",
    phone: "99976 24250",
    description: "Contact: Mr.Akhilesh Sharma",
    sourceUrl: "local://members-directory/plastic-plastic-packaging/excel-pack-pvt-ltd",
  },
  {
    name: "Fresh Pet Pvt.Ltd.",
    slug: "fresh-pet-pvt-ltd",
    category: "Plastic & Plastic Packaging",
    address: "Plot No.7,Sector-12,IIE Sidcul Haridwar",
    phone: "90900 00063",
    description: "Contact: Mr.Sachin Bharti Ji",
    sourceUrl: "local://members-directory/plastic-plastic-packaging/fresh-pet-pvt-ltd",
  },
  {
    name: "Hamilton Housewares Pvt.Ltd.",
    slug: "hamilton-housewares-pvt-ltd",
    category: "Plastic & Plastic Packaging",
    address: "Plot No.1b,Sector-12,IIE Sidcul Haridwar",
    phone: "89540 20007",
    description: "Contact: Mr.Rajan Kapoor Ji",
    sourceUrl: "local://members-directory/plastic-plastic-packaging/hamilton-housewares-pvt-ltd",
  },
  {
    name: "Kaane Packaging Pvt.Ltd.",
    slug: "kaane-packaging-pvt-ltd",
    category: "Plastic & Plastic Packaging",
    address: "Plot No.1-2,Sector-4,IIE Sidcul Haridwar",
    phone: "73510 03644",
    description: "Contact: Mr.Suyash Walia Ji",
    sourceUrl: "local://members-directory/plastic-plastic-packaging/kaane-packaging-pvt-ltd",
  },
  {
    name: "TMR Ploy tube",
    slug: "tmr-ploy-tube",
    category: "Plastic & Plastic Packaging",
    address: "Plot No-20,21 Sec-4,SIDCUL",
    phone: "9719195555",
    description: "Contact: RAJIV JAIN",
    sourceUrl: "local://members-directory/plastic-plastic-packaging/tmr-ploy-tube",
  },
  {
    name: "Aludecor Lamination Pvt Ltd",
    slug: "aludecor-lamination-pvt-ltd",
    category: "Plastic & Plastic Packaging",
    address: "Plot No.95,97,Sec-5,SIDCUL'",
    phone: "9045858540",
    description: "Contact: NISHANT",
    sourceUrl: "local://members-directory/plastic-plastic-packaging/aludecor-lamination-pvt-ltd",
  },
  {
    name: "AMCOR",
    slug: "amcor",
    category: "Plastic & Plastic Packaging",
    address: "Plot No-F-1,Sec-7,SIDCUL",
    phone: "7060004103",
    description: "Contact: NAVEEN SHARMA",
    sourceUrl: "local://members-directory/plastic-plastic-packaging/amcor",
  },
  {
    name: "M.K. PRINT PACK",
    slug: "m-k-print-pack",
    category: "Plastic & Plastic Packaging",
    address: "BAHADRABAD HARIDWAR",
    phone: "93599 08870",
    description: "Contact: MANNU",
    sourceUrl: "local://members-directory/plastic-plastic-packaging/m-k-print-pack",
  },
  {
    name: "LIBRA ENTERPRISES",
    slug: "libra-enterprises",
    category: "Plastic & Plastic Packaging",
    address: "PLOT NO.1,SCE-3A Sidcul Haridwar",
    phone: "9997949460",
    description: "Contact: Mr.AKASH SINGHAL Ji",
    sourceUrl: "local://members-directory/plastic-plastic-packaging/libra-enterprises",
  },
  {
    name: "Classic Indust",
    slug: "classic-indust",
    category: "Plastic & Plastic Packaging",
    address: "Plot No.27Sec-5 Sidcul Haridwar",
    phone: "9258022527",
    description: "Contact: Mr.PAWAN GOYAL Ji",
    sourceUrl: "local://members-directory/plastic-plastic-packaging/classic-indust",
  },
  {
    name: "shree maa roll wpa",
    slug: "shree-maa-roll-wpa",
    category: "Plastic & Plastic Packaging",
    address: "PLOT NO-6,SECTOR-6A,SIDCUL HARIDWAR",
    phone: "9897782329",
    description: "Contact: MS.SIMMI GOEL Ji",
    sourceUrl: "local://members-directory/plastic-plastic-packaging/shree-maa-roll-wpa",
  },
  {
    name: "BALAJI PACKAGING",
    slug: "balaji-packaging",
    category: "Plastic & Plastic Packaging",
    address: "IP-2,SALEMPUR MEHDOOD HARIDWAR",
    phone: "9791670088",
    description: "Contact: Mr.VINAY SHARMA Ji",
    sourceUrl: "local://members-directory/plastic-plastic-packaging/balaji-packaging",
  },
  {
    name: "Organic Plast",
    slug: "organic-plast",
    category: "Plastic & Plastic Packaging",
    address: "C-34,Sigaddi Growth Centre,Kotdwar,Uttarakhand",
    phone: "9002676820",
    description: "Contact: Mr.ANISHA SHAH Ji",
    sourceUrl: "local://members-directory/plastic-plastic-packaging/organic-plast",
  },
  {
    name: "AUTOFIT PVT LTD",
    slug: "autofit-pvt-ltd",
    category: "Plastic & Plastic Packaging",
    address: "PLOT NO.3P SEC-10 SIDCUL HARIDWAR",
    phone: "9557429292/9690288777",
    description: "Contact: MR.UMESH RAWAT JI/MR.MANOKARAN JI",
    sourceUrl: "local://members-directory/plastic-plastic-packaging/autofit-pvt-ltd",
  },
  {
    name: "ASIAN PLASTO  INDUSTRIES",
    slug: "asian-plasto-industries",
    category: "Plastic & Plastic Packaging",
    address: "PLOT NO-34, SEC-11 SIDCUL HARIDWAR",
    phone: "9520954684",
    description: "Contact: MR.R.K.SETHI JI",
    sourceUrl: "local://members-directory/plastic-plastic-packaging/asian-plasto-industries",
  },
  {
    name: "LIFELONG INDIA Pvt.Ltd",
    slug: "lifelong-india-pvt-ltd",
    category: "Plastic & Plastic Packaging",
    address: "IP-2,SALEMPUR MEHDOOD HARIDWAR",
    phone: "83938 84300",
    description: "Contact: MR.MOHAN PRASAD JI",
    sourceUrl: "local://members-directory/plastic-plastic-packaging/lifelong-india-pvt-ltd",
  },
  {
    name: "Organic Plast",
    slug: "organic-plast",
    category: "Plastic & Plastic Packaging",
    address: "C-34,Sigaddi Growth Centre,Kotdwar,Uttarakhand",
    phone: "9002676820",
    description: "Contact: MR.ANISHA SHAH JI",
    sourceUrl: "local://members-directory/plastic-plastic-packaging/organic-plast",
  },
] as const;

async function main() {
  let created = 0;
  let updated = 0;

  for (const member of MEMBERS) {
    const existing = await prisma.directoryCompany.findUnique({
      where: { sourceUrl: member.sourceUrl },
    });

    // slug must stay unique across the whole directory; nudge on collision
    // with a different company.
    let slug: string = member.slug;
    if (!existing) {
      let i = 2;
      while (await prisma.directoryCompany.findUnique({ where: { slug } })) {
        slug = `${member.slug}-${i++}`;
      }
    }

    await prisma.directoryCompany.upsert({
      where: { sourceUrl: member.sourceUrl },
      create: {
        name: member.name,
        slug,
        category: member.category,
        address: member.address ?? undefined,
        phone: member.phone ?? undefined,
        description: member.description ?? undefined,
        sourceUrl: member.sourceUrl,
      },
      update: {
        name: member.name,
        category: member.category,
        address: member.address ?? undefined,
        phone: member.phone ?? undefined,
        description: member.description ?? undefined,
      },
    });

    if (existing) updated++;
    else created++;
  }

  console.log(`Members directory seed complete: ${created} created, ${updated} updated.`);
  console.log(`Total directory companies in DB: ${await prisma.directoryCompany.count()}`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
